version: "3.7"

services:
    loja-migufe:
        image: postgres
        container_name: loja-migufe
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER='user'
            - POSTGRES_PASSWORD='password'
            - POSTGRES_DB='database'
        volumes: 
            - pgdata:/data/postgres
    # app:
    #     build: .
    #     container_name: loja-migufe
    #     ports: 
    #         - 3333:3333
    #     volumes:
    #         - .:/usr/app

volumes: 
    pgdata:
        driver: local